export interface Plant {
  id: number;
  name: string;
  variant?: string;
  size: 'S' | 'M' | 'L';
  lastWatered: string;
  dormancy?: 'Summer' | 'Winter';
  lightLevel: 'High' | 'Low';
  waterNeeds: 'High' | 'Low';
}

export const data: Plant[] = [
  {
    id: 1,
    name: 'Adenium obesum',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 2,
    name: 'Agave titanota',
    variant: 'Black and blue',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 3,
    name: 'Agave titanota',
    variant: 'Black flame',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 4,
    name: 'Agave titanota',
    variant: 'Black whale',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 5,
    name: 'Aloe marlothii',
    variant: 'Ingot',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'High',
  },
  {
    id: 6,
    name: 'Dorstenia foetida',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'High',
  },
  {
    id: 7,
    name: 'Dinteranthus vanzyliis',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 8,
    name: 'Euphorbia ferox',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 9,
    name: 'Euphorbia ferox',
    size: 'L',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 10,
    name: 'Euphorbia cocklebur',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 11,
    name: 'Euphorbia cocklebur',
    size: 'L',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 12,
    name: 'Euphorbia inermis',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 13,
    name: 'Haworthia cooperi',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'High',
  },
  {
    id: 14,
    name: 'Haworthia pygmaea',
    variant: 'Ice diamond',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'High',
  },
  {
    id: 15,
    name: 'Lithops',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 16,
    name: 'Lithops',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 17,
    name: 'Lithops',
    size: 'L',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 18,
    name: 'Mammillaria longimamma',
    variant: 'Monstruosa',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 19,
    name: 'Phyllanthus mirabilis',
    size: 'L',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'High',
  },
  {
    id: 20,
    name: 'Phyllanthus mirabilis',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'High',
  },
  {
    id: 21,
    name: 'Pseudolithos',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'Low',
  },
  {
    id: 22,
    name: 'Portulaca molokiniensis',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'High',
  },
  {
    id: 23,
    name: 'Portulaca molokiniensis',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'High',
  },
  {
    id: 24,
    name: 'Portulaca molokiniensis',
    size: 'L',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Summer',
    lightLevel: 'High',
    waterNeeds: 'High',
  },
  {
    id: 25,
    name: 'Senecio mweroensis',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'High',
  },
  {
    id: 26,
    name: 'Tulista pumila',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 27,
    name: 'Tulista pumila',
    size: 'L',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'High',
    waterNeeds: 'Low',
  },
  {
    id: 28,
    name: 'Lophophora williamsii',
    size: 'S',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'Low',
  },
  {
    id: 29,
    name: 'Lophophora williamsii',
    size: 'M',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'Low',
  },
  {
    id: 30,
    name: 'Lophophora williamsii',
    size: 'L',
    lastWatered: '1970-01-01T00:00:00Z',
    dormancy: 'Winter',
    lightLevel: 'Low',
    waterNeeds: 'Low',
  },
];
